[package]
name = "rust-game"
version = "0.1.0"
authors = ["Marc-Andre Giroux <xuorig@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4.0"
